version: '3.9'


# Default ${TEAMCITY_VERSION} is defined in .env file

# ./data_dir - TeamCity data directory
# ./teamcity-logs - logs of primary TeamCity server
# ./agents/agent-1/conf - configuration directory for the first build agent


services:
  teamcity:
    image: jetbrains/teamcity-server:latest
    ports:
      - "80:8111"
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./teamcity-server-logs:/opt/teamcity/logs
    deploy:
      mode: replicated
      replicas: 1


  teamcity-agent-1:
    image: jetbrains/teamcity-agent:latest
    privileged: true
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./agents/agent-1/conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start

networks:
  team:
    driver: overlay
    attachable: true